[2025-07-09T14:50:36.324+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: dag_pipeline_avantages.analyser_activites_sportives manual__2025-07-09T14:50:34.848872+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
